### ISSUE TITLE
Error:  Downloaded package's version does not satisfy requested version range: wanted 0.1.12 got 0.1.11.

### ISSUE THREAD

**Issue by INTIMSOCIAL** [pragmagic/uuids#11]
Nimble install wont work to get latest package version, even if i do a direct install via github link

**Comment by INTIMSOCIAL** [comment]
` Reading official package list
Downloading https://github.com/pragmagic/uuids using git
    Cloning latest tagged version: v0.1.12
download.nim(502)        downloadPkg

    Error:  Downloaded package's version does not satisfy requested version range: wanted 0.1.12 got 0.1.11.
     Info:  Nimble data file "C:\Users\alokiar\.nimble\nimbledata2.json" has been saved.`

**Comment by endragor** [comment]
My apologies, should be fixed now.
